Add functions

diff --git a/xray-install b/xray-install
--- a/xray-install
+++ b/xray-install
@@ -1,32 +1,31 @@
 #!/bin/bash
-set -e
-
 function isRoot() {
-	if [ "$EUID" -ne 0 ]; then
-		return 1
-	fi
+    if [ "$EUID" -ne 0 ]; then
+        return 1
+    fi
 }
 
 function initialCheck() {
-	if ! isRoot; then
-		echo "Sorry, you need to run this script as root."
-		exit 1
-	fi
+    if ! isRoot; then
+        echo "Sorry, you need to run this script as root."
+        exit 1
+    fi
 }
 
 function installQuestions() {
-	echo "Welcome to the Xray-core installer!"
-	echo "The git repository is available at: https://github.com/wwwean/xray-core-install"
-	echo ""
+    echo "Welcome to the Xray-core installer!"
+    echo "The git repository is available at: https://github.com/wwwean/xray-core-install"
+    echo ""
 
     echo ""
-	APPROVE_INSTALL=${APPROVE_INSTALL:-n}
-	if [[ $APPROVE_INSTALL =~ n ]]; then
-		read -n1 -r -p "Press any key to continue..."
-	fi
+    APPROVE_INSTALL=${APPROVE_INSTALL:-n}
+    if [[ $APPROVE_INSTALL =~ n ]]; then
+        read -n1 -r -p "Press any key to continue..."
+    fi
 }
 
 function installXray() {
+    # Установка Xray-core
     apt update
     apt install qrencode curl jq -y
 
@@ -41,7 +40,7 @@ function installXray() {
         echo "bbr включен"
     fi
 
-    # Устанавливаем ядро Xray
+    # Устанавливаем ядро Xray-core
     bash -c "$(curl -4 -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
     [ -f /usr/local/etc/xray/.keys ] && rm /usr/local/etc/xray/.keys
     touch /usr/local/etc/xray/.keys
@@ -143,49 +142,97 @@ function installXray() {
     }
 EOF
 
-    # Исполняемый файл для списка клиентов
-    touch /usr/local/bin/userlist
-    cat <<EOF | sed -r 's/^ {4}//' > /usr/local/bin/userlist
-    #!/bin/bash
-    emails=($(jq -r '.inbounds[0].settings.clients[].email' "/usr/local/etc/xray/config.json"))
+    # Script to add/remove Firewall rules
+    mkdir -p /etc/iptables
+    NIC=$(ip -4 route ls | grep default | grep -Po '(?<=dev )(\S+)' | head -1)
+    port=443
 
-    if [[ ${#emails[@]} -eq 0 ]]; then
-        echo "Список клиентов пуст"
-        exit 1
+    cat <<EOF | sed -r 's/^ {4}//' > /etc/iptables/add-xray-fwrules.sh
+    #!/bin/sh
+    iptables -I INPUT 1 -i $NIC -p tcp --dport $port -j ACCEPT
+EOF
+
+    cat <<EOF | sed -r 's/^ {4}//' > /etc/iptables/rm-xray-fwrules.sh
+    #!/bin/sh
+    iptables -D INPUT -i $NIC -p tcp --dport $port -j ACCEPT
+EOF
+    chmod +x /etc/iptables/add-xray-fwrules.sh
+    chmod +x /etc/iptables/rm-xray-fwrules.sh
+
+    # Handle the Firewall rules via a systemd script
+    cat <<EOF | sed -r 's/^ {4}//' > /etc/systemd/system/firewall-xray.service
+    [Unit]
+    Description=Firewall rules for Xray-core
+    BindsTo=xray.service
+    After=xray.service
+
+    [Service]
+    Type=oneshot
+    ExecStart=/etc/iptables/add-xray-fwrules.sh
+    ExecStop=/etc/iptables/rm-xray-fwrules.sh
+    RemainAfterExit=yes
+
+    [Install]
+    RequiredBy=xray.service
+EOF
+
+    # Enable service and apply Firewall rules
+    systemctl daemon-reload
+    systemctl reenable firewall-xray
+    systemctl restart xray
+
+    echo "Xray-core успешно установлен"
+    mainuser
+
+    # Создаем файл с подсказками
+    touch $HOME/help
+    cat <<EOF | sed -r 's/^ {4}//' > $HOME/help
+
+    Файл конфигурации находится по адресу:
+        /usr/local/etc/xray/config.json
+
+    Команда для перезагрузки ядра Xray:
+        systemctl restart xray
+EOF
+}
+
+function removeXray() {
+    # Удаление Xray-core
+    echo ""
+    read -rp "Do you really want to remove Xray-core? [y/n]: " -e -i n REMOVE
+    if [[ $REMOVE == 'y' ]]; then
+        # Stop and remove Xray-core and service
+        systemctl disable xray
+        systemctl stop xray
+        bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ remove
+
+        # Remove Firewall related service and scripts
+        systemctl disable firewall-xray
+        systemctl stop firewall-xray
+        rm -f /etc/systemd/system/firewall-xray.service
+        systemctl daemon-reload
+        rm -f /etc/iptables/add-xray-fwrules.sh
+        rm -f /etc/iptables/rm-xray-fwrules.sh
+
+        # Cleanup
+        rm -f /usr/local/etc/xray/config.json
+        rm -f /usr/local/etc/xray/.keys
+        rm -f /usr/local/bin/userlist
+        rm -f /usr/local/bin/mainuser
+        rm -f /usr/local/bin/newuser
+        rm -f /usr/local/bin/rmuser
+        rm -f /usr/local/bin/sharelink
+
+        echo ""
+        echo "Xray-core removed!"
+    else
+        echo ""
+        echo "Removal aborted!"
     fi
+}
 
-    echo "Список клиентов:"
-    for i in "${!emails[@]}"; do
-        echo "$((i+1)). ${emails[$i]}"
-    done
-EOF
-    chmod +x /usr/local/bin/userlist
-
-    # Исполняемый файл для ссылки основного пользователя
-    touch /usr/local/bin/mainuser
-    cat <<EOF | sed -r 's/^ {4}//' > /usr/local/bin/mainuser
-    #!/bin/bash
-    protocol=$(jq -r '.inbounds[0].protocol' /usr/local/etc/xray/config.json)
-    port=$(jq -r '.inbounds[0].port' /usr/local/etc/xray/config.json)
-    uuid=$(cat /usr/local/etc/xray/.keys | awk -F': ' '/uuid/ {print $2}')
-    pbk=$(cat /usr/local/etc/xray/.keys | awk -F': ' '/Public key/ {print $2}')
-    sid=$(cat /usr/local/etc/xray/.keys | awk -F': ' '/shortsid/ {print $2}')
-    sni=$(jq -r '.inbounds[0].streamSettings.realitySettings.serverNames[0]' /usr/local/etc/xray/config.json)
-    ip=$(timeout 3 curl -4 -s icanhazip.com)
-    link="$protocol://$uuid@$ip:$port?security=reality&sni=$sni&fp=firefox&pbk=$pbk&sid=$sid&spx=/&type=tcp&flow=xtls-rprx-vision&encryption=none#vless-$ip"
-    echo ""
-    echo "Ссылка для подключения":
-    echo "$link"
-    echo ""
-    echo "QR-код:"
-    echo ${link} | qrencode -t ansiutf8
-EOF
-    chmod +x /usr/local/bin/mainuser
-
-    # Исполняемый файл для создания новых клиентов
-    touch /usr/local/bin/newuser
-    cat <<EOF | sed -r 's/^ {4}//' > /usr/local/bin/newuser
-    #!/bin/bash
+function addUser() {
+    # Cоздание новых пользователей
     read -p "Введите имя пользователя (email): " email
 
     if [[ -z "$email" || "$email" == *" "* ]]; then
@@ -214,17 +261,14 @@ EOF
         echo ""
         echo "QR-код:"
         echo ${link} | qrencode -t ansiutf8
-        else
+    else
         echo "Пользователь с таким именем уже существует. Попробуйте снова." 
     fi
-EOF
-    chmod +x /usr/local/bin/newuser
+}
 
-    # Исполняемый файл для удаления клиентов
-    touch /usr/local/bin/rmuser
-    cat <<EOF | sed -r 's/^ {4}//' > /usr/local/bin/rmuser
-    #!/bin/bash
-    emails=($(jq -r '.inbounds[0].settings.clients[].email' "/usr/local/etc/xray/config.json"))
+function removeUser() {
+    # Удаление пользователей
+    emails=($(jq -r '.inbounds[0].settings.clients[].email' /usr/local/etc/xray/config.json))
 
     if [[ ${#emails[@]} -eq 0 ]]; then
         echo "Нет клиентов для удаления."
@@ -237,28 +281,20 @@ EOF
     done
 
     read -p "Введите номер клиента для удаления: " choice
-
     if ! [[ "$choice" =~ ^[0-9]+$ ]] || (( choice < 1 || choice > ${#emails[@]} )); then
         echo "Ошибка: номер должен быть от 1 до ${#emails[@]}"
         exit 1
     fi
 
     selected_email="${emails[$((choice - 1))]}"
-
-    jq --arg email "$selected_email" \
-    '(.inbounds[0].settings.clients) |= map(select(.email != $email))' \
-    "/usr/local/etc/xray/config.json" > tmp && mv tmp "/usr/local/etc/xray/config.json"
+    jq --arg email "$selected_email" '(.inbounds[0].settings.clients) |= map(select(.email != $email))' /usr/local/etc/xray/config.json > tmp.json && mv tmp.json /usr/local/etc/xray/config.json
 
     systemctl restart xray
-
     echo "Клиент $selected_email удалён."
-EOF
-    chmod +x /usr/local/bin/rmuser
+}
 
-    # Исполняемый файл для вывода списка пользователей и создания ссылкок
-    touch /usr/local/bin/sharelink
-    cat <<EOF | sed -r 's/^ {4}//' > /usr/local/bin/sharelink
-    #!/bin/bash
+function listUser() {
+    # Вывод списка пользователей и создание ссылкок для их подключения
     emails=($(jq -r '.inbounds[0].settings.clients[].email' /usr/local/etc/xray/config.json))
 
     for i in "${!emails[@]}"; do
@@ -266,14 +302,13 @@ EOF
     done
 
     read -p "Выберите клиента: " client
-
     if ! [[ "$client" =~ ^[0-9]+$ ]] || (( client < 1 || client > ${#emails[@]} )); then
         echo "Ошибка: номер должен быть от 1 до ${#emails[@]}"
         exit 1
     fi
 
     selected_email="${emails[$((client - 1))]}"
-    index=$(jq --arg email "$selected_email" '.inbounds[0].settings.clients | to_entries[] | select(.value.email == $email) | .key'  /usr/local/etc/xray/config.json)
+    index=$(jq --arg email "$selected_email" '.inbounds[0].settings.clients | to_entries[] | select(.value.email == $email) | .key' /usr/local/etc/xray/config.json)
     protocol=$(jq -r '.inbounds[0].protocol' /usr/local/etc/xray/config.json)
     port=$(jq -r '.inbounds[0].port' /usr/local/etc/xray/config.json) 
     uuid=$(jq --argjson index "$index" -r '.inbounds[0].settings.clients[$index].id' /usr/local/etc/xray/config.json)
@@ -289,149 +324,43 @@ EOF
     echo ""
     echo "QR-код:"
     echo ${link} | qrencode -t ansiutf8
-EOF
-    chmod +x /usr/local/bin/sharelink
-
-    # Script to add Firewall rules
-    NIC=$(ip -4 route ls | grep default | grep -Po '(?<=dev )(\S+)' | head -1)
-
-    cat <<EOF | sed -r 's/^ {4}//' > /etc/iptables/add-xray-fwrules.sh
-	#!/bin/sh
-    iptables -I INPUT 1 -i $NIC -p tcp --dport 443 -j ACCEPT
-EOF
-
-	# Script to remove Firewall rules
-    cat <<EOF | sed -r 's/^ {4}//' > /etc/iptables/rm-xray-fwrules.sh
-	#!/bin/sh
-    iptables -D INPUT -i $NIC -p tcp --dport 443 -j ACCEPT
-EOF
-	chmod +x /etc/iptables/add-xray-fwrules.sh
-	chmod +x /etc/iptables/rm-xray-fwrules.sh
-
-	# Handle the Firewall rules via a systemd script
-    cat <<EOF | sed -r 's/^ {4}//' > /etc/systemd/system/firewall-xray.service
-	[Unit]
-    Description=Firewall rules for Xray-core
-    BindsTo=xray.service
-    After=xray.service
-
-    [Service]
-    Type=oneshot
-    ExecStart=/etc/iptables/add-xray-fwrules.sh
-    ExecStop=/etc/iptables/rm-xray-fwrules.sh
-    RemainAfterExit=yes
-
-    [Install]
-    RequiredBy=xray.service
-EOF
-
-	# Enable service and apply Firewall rules
-	systemctl daemon-reload
-	systemctl reenable firewall-xray
-    systemctl restart xray
-
-    echo "Xray-core успешно установлен"
-    mainuser
-
-    # Создаем файл с подсказками
-    touch $HOME/help
-    cat <<EOF | sed -r 's/^ {4}//' > $HOME/help
-
-    Команды для управления пользователями Xray:
-
-        mainuser - выводит ссылку для подключения основного пользователя
-        newuser - создает нового пользователя
-        rmuser - удаление пользователей
-        sharelink - выводит список пользователей и позволяет создать для них ссылки для подключения
-        userlist - выводит список клиентов
-
-    Файл конфигурации находится по адресу:
-
-        /usr/local/etc/xray/config.json
-
-    Команда для перезагрузки ядра Xray:
-
-        systemctl restart xray
-EOF
-}
-
-function removeXray() {
-	echo ""
-	read -rp "Do you really want to remove Xray-core? [y/n]: " -e -i n REMOVE
-	if [[ $REMOVE == 'y' ]]; then
-		# Stop and remove Xray-core and service
-        systemctl disable xray
-        systemctl stop xray
-        bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ remove
-
-        # Remove Firewall related service and scripts
-		systemctl stop firewall-xray
-		systemctl disable firewall-xray
-		rm -f /etc/systemd/system/firewall-xray.service
-		systemctl daemon-reload
-		rm -f /etc/iptables/add-xray-fwrules.sh
-		rm -f /etc/iptables/rm-xray-fwrules.sh
-
-		# Cleanup
-		rm -f /usr/local/etc/xray/config.json
-        rm -f /usr/local/etc/xray/.keys
-        rm -f /usr/local/bin/userlist
-        rm -f /usr/local/bin/mainuser
-        rm -f /usr/local/bin/newuser
-        rm -f /usr/local/bin/rmuser
-        rm -f /usr/local/bin/sharelink
-
-		echo ""
-		echo "Xray-core removed!"
-	else
-		echo ""
-		echo "Removal aborted!"
-	fi
 }
 
 function manageMenu() {
-	echo "Welcome to Xray-core-install!"
-	echo "The git repository is available at: https://github.com/wwwean/xray-core-install"
-	echo ""
-	echo "It looks like Xray-core is already installed."
-	echo ""
-	echo "What do you want to do?"
-	echo "   1) Add a new user"
-    echo "   2) Main user"
-    echo "   3) User list"
-    echo "   4) Make sharelink"
-	echo "   5) Revoke existing user"
-	echo "   6) Remove Xray-core"
-	echo "   7) Exit"
+    echo "Welcome to Xray-core-install!"
+    echo "The git repository is available at: https://github.com/wwwean/xray-core-install"
+    echo ""
+    echo "It looks like Xray-core is already installed."
+    echo ""
+    echo "What do you want to do?"
+    echo "   1) Add a new user"
+    echo "   2) List of users and sharelink"
+    echo "   3) Revoke existing user"
+    echo "   4) Remove Xray-core"
+    echo "   5) Exit"
     echo ""
 
-	until [[ $MENU_OPTION =~ ^[1-7]$ ]]; do
-		read -rp "Select an option [1-7]: " MENU_OPTION
-	done
+    until [[ $MENU_OPTION =~ ^[1-7]$ ]]; do
+        read -rp "Select an option [1-5]: " MENU_OPTION
+    done
 
-	case $MENU_OPTION in
-	1)
-		newuser
-		;;
-	2)
-        mainuser
+    case $MENU_OPTION in
+    1)
+        addUser
+        ;;
+    2)
+        listUser
         ;;
     3)
-        userlist
+        removeUser
         ;;
     4)
-		sharelink
-		;;
+        removeXray
+        ;;
     5)
-		rmuser
-		;;
-	6)
-		removeXray
-		;;
-	7)
-		exit 0
-		;;
-	esac
+        exit 0
+        ;;
+    esac
 }
 
 # Check for root
