Add remove func. Ext menu

diff --git a/xray-install b/xray-install
--- a/xray-install
+++ b/xray-install
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
+
 function isRoot() {
 	if [ "$EUID" -ne 0 ]; then
 		return 1
@@ -322,6 +324,32 @@ EOF
 EOF
 }
 
+function removeXray() {
+	echo ""
+	read -rp "Do you really want to remove Xray-core? [y/n]: " -e -i n REMOVE
+	if [[ $REMOVE == 'y' ]]; then
+		# Stop and remove Xray-core
+        systemctl disable xray
+        systemctl stop xray
+        bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ remove
+
+		# Cleanup
+		rm -f /usr/local/etc/xray/config.json
+        rm -f /usr/local/etc/xray/.keys
+        rm -f /usr/local/bin/userlist
+        rm -f /usr/local/bin/mainuser
+        rm -f /usr/local/bin/newuser
+        rm -f /usr/local/bin/rmuser
+        rm -f /usr/local/bin/sharelink
+
+		echo ""
+		echo "Xray-core removed!"
+	else
+		echo ""
+		echo "Removal aborted!"
+	fi
+}
+
 function manageMenu() {
 	echo "Welcome to Xray-core-install!"
 	echo "The git repository is available at: https://github.com/wwwean/xray-core-install"
@@ -330,13 +358,15 @@ function manageMenu() {
 	echo ""
 	echo "What do you want to do?"
 	echo "   1) Add a new user"
-	echo "   2) Revoke existing user"
-	echo "   3) Remove OpenVPN"
-	echo "   4) Exit"
+    echo "   2) Main user"
+    echo "   3) User list"
+	echo "   4) Revoke existing user"
+	echo "   5) Remove Xray-core"
+	echo "   6) Exit"
     echo ""
 
-	until [[ $MENU_OPTION =~ ^[1-4]$ ]]; do
-		read -rp "Select an option [1-4]: " MENU_OPTION
+	until [[ $MENU_OPTION =~ ^[1-6]$ ]]; do
+		read -rp "Select an option [1-6]: " MENU_OPTION
 	done
 
 	case $MENU_OPTION in
@@ -344,12 +374,18 @@ function manageMenu() {
 		newuser
 		;;
 	2)
+        mainuser
+        ;;
+    3)
+        userlist
+        ;;
+    4)
 		rmuser
 		;;
-	3)
+	5)
 		removeXray
 		;;
-	4)
+	6)
 		exit 0
 		;;
 	esac
